<a href="https://colab.research.google.com/github/MarAndreaFernandez/Bases-Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from numpy import random

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


0-D Arrays, o escalares

In [ ]:
a0 = np.array(42)
print(a0)

42


1-D Array


In [ ]:
a1 = np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [ ]:
2-D Array

In [ ]:
a2 = np.array([(1,2,3,4),(4,3,2,1)])
print(a2)

[[1 2 3 4]
 [4 3 2 1]]


3-D Array

In [ ]:
a3 = np.array([[(1,2,3,4),(4,3,2,1)],[(1,2,3,4),(4,3,2,1)]])
print(a3)

[[[1 2 3 4]
  [4 3 2 1]]

 [[1 2 3 4]
  [4 3 2 1]]]


In [ ]:
ndim nos da las dimensiones de un array

In [ ]:
print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


0
1
2
3


Podemos definir las dimensiones de nuestro array

In [ ]:
arr = np.array([1,2,3,4], ndmin = 5)

print(arr)

print('El numero de dimensiones es: ', arr.ndim)

[[[[[1 2 3 4]]]]]
El numero de dimensiones es:  5


**Indexing**

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Segundo elemento de la primer renglon: ', arr[0,1])
print('Segundo renglon, quinta columna: ', arr[1,4])

Segundo elemento de la primer renglon:  2
Segundo renglon, quinta columna:  10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('Tercer elemento de el segundo array del primer array: ', arr[0,1,2])

Tercer elemento de el segundo array del primer array:  6


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Ultimo elemnto de la segunda dimension', arr[1,-1])

Ultimo elemnto de la segunda dimension 10


**Slicing**

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-4:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[4 5 6]
[2 4]
[1 3 5 7]


View vs Copy

In [8]:
arr= np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [11]:
arr= np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
x[1]= 10
print(arr)
print(x)

[42 10  3  4  5]
[42 10  3  4  5]


In [10]:
arr= np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


shape

In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [15]:
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)
print(arr.shape)


[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


reshape

In [28]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
newarr2= arr.reshape(2,3,2)
print(newarr)
print(newarr2)
print(newarr.base)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
print(newarr)
flat = newarr.reshape(-1)
print(flat)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


Iteraciones

In [32]:
arr = np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [34]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [37]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [38]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [39]:
arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [41]:
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [42]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Juntar arreglos

In [44]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.concatenate((arr1,arr2), axis=1)
print(arr3)
arr3 = np.concatenate((arr1,arr2), axis=0)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.stack((arr1, arr2), axis=1)

print(arr)
arr = np.hstack((arr1, arr2))

print(arr)
arr = np.vstack((arr1, arr2))

print(arr)
arr = np.dstack((arr1, arr2))

print(arr)


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [55]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)
newarr = np.array_split(arr,4)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5]


In [61]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr,3)
print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [5]:
arr= np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)
x = np.where(arr%2 == 0)
print(x)
x = np.where(arr%2 == 1)
print(x)
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


In [8]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

arr = np.array([True, False, True])

print(np.sort(arr))

['apple' 'banana' 'cherry']
[False  True  True]


In [6]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [12]:
arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

arr = np.array([41,42,43,44])

filter_arr = []

for element in arr:
  if element >= 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[41 43]
[False, True, True, True]
[42 43 44]


In [15]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = []
for element in arr:
  if element%2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [16]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42
newarr = arr[filter_arr]
print(newarr)

[43 44]


Random Numbers

In [9]:
x = random.randint(100)
print(x)

x = random.rand()
print(x)

64
0.7218811786919389


In [17]:
x = random.randint(100, size =(5))
print(x)
x = random.randint(100, size =(3,5))
print(x)
x = random.rand(5,2)
print(x)

[39 11 35 32 22]
[[39 59 24 96 21]
 [31 86 79 87 37]
 [90 47 21 32  5]]
[[0.20904746 0.78005168]
 [0.24926708 0.87288291]
 [0.88514062 0.65519323]
 [0.20310786 0.61950272]
 [0.14848168 0.32730232]]


In [24]:
y = random.choice([1,2,3,4,5,6])
z = random.choice([1,2,3,4,5,6], size = (3,5))
print(z)

[[5 3 1 5 6]
 [3 3 5 5 5]
 [5 4 6 4 1]]
